// Code generated by hertz generator.

package api

import (
	"context"
	"encoding/json"
	"github.com/FantasyRL/go-mcp-demo/pkg/errno"
	"github.com/FantasyRL/go-mcp-demo/pkg/utils"
	"io"

	api "github.com/FantasyRL/go-mcp-demo/api/model/api"
	"github.com/FantasyRL/go-mcp-demo/api/pack"
	"github.com/FantasyRL/go-mcp-demo/internal/host/application"
	"github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/hertz/pkg/protocol/sse"
)

// Chat .
// @router /api/v1/chat [POST]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 处理图片上传
	var imageData []byte
	file, err := c.FormFile("image")
	if err == nil && file != nil {
		// 打开上传的文件
		src, err := file.Open()
		if err != nil {
			pack.RespError(c, err)
			return
		}
		defer src.Close()

		// 读取文件内容
		imageData, err = io.ReadAll(src)
		if err != nil {
			pack.RespError(c, err)
			return
		}
	}

	resp := new(api.ChatResponse)
	uid, ok := utils.ExtractStuID(ctx)
	if !ok {
		pack.RespError(c, errno.AuthInvalid)
		return
	}
	msg, err := application.NewHost(ctx, clientSet).ChatOpenAI(uid, req.ConversationID, req.Message, imageData)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.Response = msg
	pack.RespData(c, resp)
}

// ChatSSE .
// @router /api/v1/chat/sse [GET]
// in: api/handler/api/chat_sse.go
func ChatSSE(ctx context.Context, c *app.RequestContext) {
	var req api.ChatSSEHandlerRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 处理图片上传
	var imageData []byte
	file, err := c.FormFile("image")
	if err == nil && file != nil {
		// 打开上传的文件
		src, err := file.Open()
		if err != nil {
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}
		defer src.Close()

		// 读取文件内容
		imageData, err = io.ReadAll(src)
		if err != nil {
			c.String(consts.StatusInternalServerError, err.Error())
			return
		}
	}

	w := sse.NewWriter(c)
	defer w.Close()

	emit := func(_ string, v any) error {
		switch x := v.(type) {
		case string: // 用于 [DONE]
			return w.WriteEvent("", "", []byte(x))
		case json.RawMessage:
			return w.WriteEvent("", "", x)
		default:
			b, _ := json.Marshal(v)
			return w.WriteEvent("", "", b)
		}
	}
	uid, ok := utils.ExtractStuID(ctx)
	if !ok {
		_ = emit("error", map[string]any{"error": "unauthorized"})
		return
	}

	if err := application.NewHost(ctx, clientSet).StreamChatOpenAI(ctx, uid, req.ConversationID, req.Message, imageData, emit); err != nil {
		_ = emit("error", map[string]any{"error": err.Error()})
		return
	}
}

// Template .
// @router /api/v1/template [POST]
func Template(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.TemplateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.TemplateResponse)
	u, err := application.NewHost(ctx, clientSet).TemplateLogic(&req)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.User = pack.BuildUserResp(u)
	pack.RespData(c, resp)
}

// SummarizeConversation .
// @router /api/v1/conversation/summarize [POST]
func SummarizeConversation(ctx context.Context, c *app.RequestContext) {
	var req api.SummarizeConversationRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	result, err := application.NewHost(ctx, clientSet).SummarizeConversation(req.ConversationID)
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := &api.SummarizeConversationResponse{
		Summary:       result.Summary,
		Tags:          result.Tags,
		ToolCallsJSON: result.ToolCallsJSON, // 统一字段名
		Notes:         result.Notes,
	}
	pack.RespData(c, resp)
}

// GetLoginData .
// @router /api/v1/user/login [POST]
func GetLoginData(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetLoginDataRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetLoginDataResponse)

	loginData, err := application.NewHost(ctx, clientSet).Login(req.StuID, req.Password)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.Identifier = loginData.Identifier
	resp.Cookie = loginData.Cookie
	resp.AccessToken = loginData.AccessToken
	pack.RespData(c, resp)
}

// GetUserInfo .
// @router /api/v1/user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	//resp := new(api.GetUserInfoResponse)

	info, err := application.NewHost(ctx, clientSet).GetUserInfo()
	if err != nil {
		pack.RespError(c, err)
		return
	}
	pack.RespData(c, info)
}

// GetConversationHistory .
// @router /api/v1/conversation/history [GET]
func GetConversationHistory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetConversationHistoryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetConversationHistoryResponse)
	uid, ok := utils.ExtractStuID(ctx)
	if !ok {
		pack.RespError(c, errno.AuthInvalid)
		return
	}

	history, err := application.NewHost(ctx, clientSet).GetConversation(uid, req.ConversationID)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.ConversationID = history.ID
	resp.Messages = history.Messages

	pack.RespData(c, resp)
}
