// Code generated by hertz generator.

package api

import (
	"github.com/FantasyRL/go-mcp-demo/api/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _chat0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _chatsseMw() []app.HandlerFunc {
	return nil
}

func _templateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _summarizeconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaccesstokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.GetHeaderParams(),
		mw.Auth(),
	}
}

func _getlogindataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversationhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}
